if has("syntax")
    syntax on
endif

set showmatch
set smartcase
set autoindent
set number
" tab
set tabstop=4
set shiftwidth=4
set expandtab
" powerline
"set laststatus=2
"set t_Co=256
"set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/

if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
endif
