if has("syntax")
    syntax on
endif

set autoindent
set autoread
" set cursorline
set showmatch
set number
set smartcase
" search
set hlsearch
set incsearch
" tab
set tabstop=4
set shiftwidth=4
set expandtab
" powerline
"set laststatus=2
"set t_Co=256
"set rtp+=$HOME/.local/lib/python3.5/site-packages/powerline/bindings/vim/

if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
endif
